# Generated by Django 3.2 on 2022-12-17 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('edition', models.IntegerField(verbose_name='Edition')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publisher', models.TextField(verbose_name='Publisher')),
                ('copies', models.IntegerField(verbose_name='No. of Copies')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(default='', null=True)),
                ('status', models.CharField(default='PENDING', max_length=100, verbose_name='status')),
                ('is_claimed', models.BooleanField(default=False)),
                ('qr_code', models.CharField(max_length=10, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book Name')),
                ('reservee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='WalkInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact No.')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(null=True)),
                ('returned_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='BORROWED', max_length=20, verbose_name='status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default='', null=True)),
                ('reserved_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookreservation')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBookRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField()),
                ('status', models.CharField(default='BORROWED', max_length=20, verbose_name='Status')),
                ('item_to_leave', models.CharField(default='ID', max_length=100, verbose_name='Item to leave')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('date_to_return', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookreservation')),
                ('walk_in_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.walkinuser')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.classification', verbose_name='genre'),
        ),
    ]
