# Generated by Django 3.2 on 2022-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbookrecords',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
