# Generated by Django 3.2 on 2022-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrowbookrecords_date_to_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbookrecords',
            name='date_to_return',
            field=models.DateTimeField(null=True),
        ),
    ]
