# Generated by Django 3.2 on 2022-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='readermoreinfo',
            name='reader_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Reader Type'),
        ),
        migrations.AddField(
            model_name='readermoreinfo',
            name='school',
            field=models.TextField(default='', verbose_name='School'),
        ),
    ]
