# Generated by Django 3.2 on 2022-06-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220618_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryStaffMoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='Department')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
