# Generated by Django 3.2 on 2022-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_librarystaffmoreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='readermoreinfo',
            name='middle_name',
            field=models.CharField(max_length=20, null=True, verbose_name='middle name'),
        ),
    ]
