# Generated by Django 3.2 on 2022-06-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_readermoreinfo_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readermoreinfo',
            name='middle_name',
        ),
    ]
