# Generated by Django 3.2 on 2022-07-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('READER', 'Reader'), ('LIBRARY STAFF', 'Library Staff')], default='READER', max_length=50),
        ),
    ]
