# Generated by Django 3.2 on 2022-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('READER', 'Reader'), ('LIBRARY_STAFF', 'Library Staff')], default='READER', max_length=50),
        ),
    ]
