# Generated by Django 3.2 on 2023-03-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarystaffmoreinfo',
            name='position',
            field=models.CharField(choices=[('STAFF', 'STAFF'), ('ADMIN', 'ADMIN')], max_length=100, null=True, verbose_name='Position'),
        ),
    ]
