# Generated by Django 3.2 on 2023-03-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_librarystaffmoreinfo_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarystaffmoreinfo',
            name='department',
        ),
    ]
