# Generated by Django 3.2 on 2023-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_librarystaffmoreinfo_date_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarystaffmoreinfo',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='librarystaffmoreinfo',
            name='birth_place',
            field=models.TextField(default=None, null=True, verbose_name='Birthplace'),
        ),
    ]
